version: "3"
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
    networks:
      - cynapse-data-network
    volumes:
      - ./data-mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./data-mosquitto/data:/mosquitto/data
      - ./data-mosquitto/log:/mosquitto/log
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    user: "1000"
    networks:
      - cynapse-data-network
    volumes:
      - /home/user/dev/data-grafana:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    networks:
      - cynapse-data-network
    volumes:
      - /home/user/dev/data-influxdb:/var/lib/influxdb
      - /home/user/dev/influxDbBackup/backup:/var/local/influxDbBackup
      - /home/user/dev/data-influxdb/config/influxdb.conf:/etc/influxdb/influxdb.conf
    environment:
      - INFLUXDB_USER=cynapse
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    #  - INFLUXDB_HTTP_FLUX_ENABLED=true
    # - INFLUXDB_HTTP_ENABLED=ture
    # - INFLUXDB_HTTP_BIND_ADDRESS=":8086"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
  chronograf:
    image: chronograf
    container_name: chronograf
    restart: always
    ports:
      - 8888:8888
    networks:
      - cynapse-data-network
    volumes:
      - chronograf-volume:/home/user/dev/data-chonograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=admin
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
  cynapse_mqtt_to_influx:
    container_name: cynapse_mqtt_to_influx_index
    build: convertCynapseMqttDataToInfluxDbData
    image: cynapse_mqtt_to_influx
    #restart: always
    depends_on:
      - influxdb
      - mosquitto
    volumes:
      - ./convertCynapseMqttDataToInfluxDbData/src:/code
    environment:
      - INFLUX_DATABASE_SERVER=DCIOLM03.wittag.net
      - INFLUX_DATABASE_SERVER_PORT=8086
      - INFLUX_DATABASE=hh-h01-index-g200
      - MQTT_BROKER=mosquitto
      - MQTT_BROKER_PORT=1883
    networks:
      - cynapse-data-network
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
networks:
  cynapse-data-network:
volumes:
  chronograf-volume:
