version: "3"
services:
  mosquitto:
    build: ./mosquitto
    image: localbuild/mosquitto:april2021
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    networks:
      - cynapse-data-network
    volumes:
      - ./data-mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./data-mosquitto/data:/mosquitto/data
      - ./data-mosquitto/log:/mosquitto/log
  grafana:
    build: ./grafana
    image: localbuild/grafana:april2021
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - cynapse-data-network
    volumes:
      - ./data-grafana:/var/lib/grafana
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
  influxdb:
    build: ./influx
    image: localbuild/influxdb:april2021
    container_name: influxdb
    restart: unless-stopped
    ports:
      - 8086:8086
    networks:
      - cynapse-data-network
    volumes:
      - ./data-influxdb:/var/lib/influxdb
      - ./influxDbBackup/backup:/var/local/influxDbBackup
      - ./data-influxdb/config/influxdb.conf:/etc/influxdb/influxdb.conf
    environment:
      INFLUXDB_DB: cynapse
      INFLUXDB_USER: cynapse
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
  cynapse_mqtt_to_influx:
    container_name: cynapse_mqtt_to_influx
    build: convertCynapseMqttDataToInfluxDbData
    image: cynapse_mqtt_to_influx
    restart: always
    depends_on:
      - influxdb
      - mosquitto
    volumes:
      - ./convertCynapseMqttDataToInfluxDbData/src:/code
    environment:
      - INFLUX_DATABASE_SERVER=localhost
      - INFLUX_DATABASE_SERVER_PORT=8086
      - INFLUX_DATABASE=cynapse
      - MQTT_BROKER=mosquitto
      - MQTT_BROKER_PORT=1883
    networks:
      - cynapse-data-network
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
networks:
  cynapse-data-network:
volumes:
  chronograf-volume:
