version: "3"
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:1.6.14
    restart: always
    ports:
      - "1883:1883"
    networks:
      - cynapse-data-network
    volumes:
      - ./data-mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./data-mosquitto/data:/mosquitto/data
      - ./data-mosquitto/log:/mosquitto/log
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    user: "1000"
    networks:
      - cynapse-data-network
    volumes:
      - ./data-grafana:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    networks:
      - cynapse-data-network
    volumes:
      - ./data-influxdb:/var/lib/influxdb
      - ./influxDbBackup/backup:/var/local/influxDbBackup
      - ./data-influxdb/config/influxdb.conf:/etc/influxdb/influxdb.conf
    environment:
      INFLUXDB_DB: cynapse
      INFLUXDB_USER: cynapse
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
    #  - INFLUXDB_HTTP_FLUX_ENABLED=true
    # - INFLUXDB_HTTP_ENABLED=ture
    # - INFLUXDB_HTTP_BIND_ADDRESS=":8086"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
  cynapse_mqtt_to_influx:
    container_name: cynapse_mqtt_to_influx
    build: convertCynapseMqttDataToInfluxDbData
    image: cynapse_mqtt_to_influx
    restart: always
    depends_on:
      - influxdb
      - mosquitto
    volumes:
      - ./convertCynapseMqttDataToInfluxDbData/src:/code
    environment:
      - INFLUX_DATABASE_SERVER=localhost
      - INFLUX_DATABASE_SERVER_PORT=8086
      - INFLUX_DATABASE=cynapse
      - MQTT_BROKER=mosquitto
      - MQTT_BROKER_PORT=1883
    networks:
      - cynapse-data-network
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
networks:
  cynapse-data-network:
volumes:
  chronograf-volume:
